### ISSUE TITLE
Feature request: Add Android x86 support

### ISSUE THREAD

**Issue by subdan** [juank-pa/JKLocalNotifications-ANE#16]
The ANE doesn't support Android x86 devices.

**Comment by juank-pa** [comment]
@subdan Are there x86 devices or is this for Android emulator?

**Comment by subdan** [comment]
Yes, There are a lot of x86 devices. I have 2 real ARM devices and 2 x86 devices. A lot of ANEs from other developers contains Android-x86 and Android ARM folders inside ANE file.
Example:
![screenshot_1](https://user-images.githubusercontent.com/410293/32493395-5dc1af04-c3c6-11e7-8e92-55ab2c5464c0.png)

**Comment by juank-pa** [comment]
OK I was asking because on PR #14 I added an ANE builder for x86 devices that I was using for emulator. But if it is also needed for real devices I'll also pack this version into the final ANE. Thanks for the feedback.

**Comment by juank-pa** [comment]
The ANE at `bin/dist`should be working for x86 devices. I'll wait for your feedback.

**Comment by subdan** [comment]
Your ANE have conflicts with ANEs I use in my app.
I use these three ANEs:

- com.distriqt.Share.ane
- com.distriqt.Core.ane
- com.distriqt.androidsupport.V4.ane

I get this error:
```
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/compat/BuildConfig;
```

---
To fix this issue I removed support-v4 and support-compat jar files from your ANE because com.distriqt.androidsupport.V4.ane already has these jar files. Now all is ok.

---
Now notifications works on Android x86 devices. Thank you, Juan!

---
ANE file size increased by 8 times. Why?

**Comment by juank-pa** [comment]
I only saw it grew three times only. Anyway the first time it grew because the Android code was completely modularized in many classes, so the base code was larger. Then, the icons were small and prepared only for Android v9, I had to create more icons and prepare them for Android v11. I didn't use a PNG compressor so maybe we can reduce the footprint if I do that. And finally adding the x86 version added even more size.

**Comment by juank-pa** [comment]
BTW I wanted to ask you how did you manage remove the files from the ANE. I tried for some time so remove them from the compiled ANE and then zip it together again but this seemed to invalidate the ANE. If there is a way to do this then I could also change or add icons to the resources to ease the usage of custom icons on Android. Thanks ind advance.

**Comment by subdan** [comment]
I opened (without decompressing) an archive in 7zip, finded jar files, removed them and closed archive. Also, I replaced icons by the same way and everything is works.

**Comment by juank-pa** [comment]
Great! this will help me update the README file to give users new options.
I tried the same you did with Extractor in Mac but seemed to have the same problem. I'll try this with 7zip to see if it works. Thanks!
