### ISSUE TITLE
Feature request: Expanded layout for Android

### ISSUE THREAD

**Issue by subdan** [juank-pa/JKLocalNotifications-ANE#17]
I send a notifications with long message. When a notification fires I don't see full text. I want to swipe to expand a notification to view full message but i can't.

https://developer.android.com/guide/topics/ui/notifiers/notifications.html
Applying an expanded layout to a notification

![screenshot_1](https://user-images.githubusercontent.com/410293/32536247-456925d6-c466-11e7-87e7-2e36400fcede.png)

**Comment by juank-pa** [comment]
Having a custom expanded mode is something I was not planning for now. Nevertheless, having simply an expanded view that shows a large text is easy and we can do that. Thanks for the suggestion.

**Comment by juank-pa** [comment]
I have implemented this in the latest version Please take a look.

**Comment by subdan** [comment]
I found ANE file only in `samples\flash_builder` folder. Is it the latest version? This ANE doesn't support x86 and doesn't contains `classes` folder for Android ARM version. So this version of ANE doesn't work at all.

**Comment by juank-pa** [comment]
Yes from now on I'm not including the binary file in the repo. I'm even going to remove that one you mentioned at some point. If you go to the Releases page then you will find a link to the binary.

**Comment by juank-pa** [comment]
https://github.com/juank-pa/JKLocalNotifications-ANE/releases

**Comment by subdan** [comment]
Do I need to change something in my code? When I try to expand a notification nothing happens.

**Comment by juank-pa** [comment]
It should be already working now. But if not maybe the uploaded binary is not the right version. I can replace the upload, but because I do this on my free time I won't be able to do it until evening. Once this is ready I can confirm this.

**Comment by juank-pa** [comment]
It is weird, I have used the ANE from release 1.0.5 and haven't got any problems, I can actually expand it. I did this on a real device and on emulators. Which Android API are you using.

**Comment by juank-pa** [comment]
Please remember the ANE is no longer getting packed in the GitHub repository and you have to getting using the download links in the release page for the latest stable version.

**Comment by subdan** [comment]
It works! Thanks!

**Comment by juank-pa** [comment]
Happy to announce the new version v1.1.0 came out of alpha and will temporarily hit beta to allow fixing bugs. You are invited to test it out and provide feedback. And don't forget to watch 
![image](https://user-images.githubusercontent.com/5060527/34040097-3d776100-e160-11e7-965f-0f7d36c22402.png) the repo to get information on new versions and features. New features include: support for sounds on Android, custom action buttons in notifications, Android heads up notifications, and more. Thanks in advance.
