### ISSUE TITLE
Feature request: Launch app at specific time

### ISSUE THREAD

**Issue by dr-mms** [juank-pa/JKLocalNotifications-ANE#21]
It will be perfect if we can launch the app in specific time instead of showing notification and passing notification parameter to the app.

**Comment by juank-pa** [comment]
@drmms86 This notification pretends to give a similar experience between iOS and Android in the way notifications work. Beside the ANE works around the idea of a notification and not a timer to open apps which I think will be kind of intrusive.

The ANE definitively has enough code to implement something like this, so if you find inspiration on it for what you want you can try implementing it. I might be able to code review you  from time to time. But for now, sadly I will not implement this feature. Hope you understand.

**Comment by dr-mms** [comment]
Thanks for your reply. I will try to implement it and tell you

**Comment by juank-pa** [comment]
Happy to announce the new version v1.1.0 came out of alpha and will temporarily hit beta to allow fixing bugs. You are invited to test it out and provide feedback. And don't forget to watch 
![image](https://user-images.githubusercontent.com/5060527/34040097-3d776100-e160-11e7-965f-0f7d36c22402.png) the repo to get information on new versions and features. New features include: support for sounds on Android, custom action buttons in notifications, Android heads up notifications, and more. Thanks in advance.
