### ISSUE TITLE
Notification when app if closed?

### ISSUE THREAD

**Issue by pahenator** [juank-pa/JKLocalNotifications-ANE#37]
Hi Juan Carlos,

Is it possible to fire notification whe application has been closed already?

Thanks for reply

**Comment by juank-pa** [comment]
Notifications should be working when the app is closed right now. If this is not happening please describe steps to reproduce, and the device type and operating system details, along with the version you are using. Thanks in advance.

**Comment by pahenator** [comment]
Thank you, I will try the latest version. I was a little bit scary to jump up from 300 kb to 1.3Mb version, but I'll try anyway. Thanks for your lib

**Comment by juank-pa** [comment]
You are welcome to try version 1.2.0. Is a lot lighter than previous versions and added more features like background button actions and text field actions.
