### ISSUE TITLE
ANE doesn't work on iOS 11.0.2

### ISSUE THREAD

**Issue by subdan** [juank-pa/JKLocalNotifications-ANE#4]
I get this error:
```
[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.
NotificationManager in NotificationManager.as:81
```

**Comment by subdan** [comment]
Also, I can't package sample app via Animate CC. I get error: Namespace is invalid in the application descriptor file.

**Comment by subdan** [comment]
Tested on Android device. I have the same error.
How to fix this issue?

**Comment by juank-pa** [comment]
This is an issue that arose with the previous feature merge I already worked on it in the current PR, but since the current PR is going to take a while to finish I can try to fix the issue sooner. I'll give new about this soon.

**Comment by subdan** [comment]
Ok. Thanks.

**Comment by juank-pa** [comment]
@subdan Can you please check if this solves your issue by checking out the PR #6 branch?

**Comment by juank-pa** [comment]
Sorry I forgot to upload the final ane. Wait a second

**Comment by subdan** [comment]
Yes, I will check it within several hours.

waiting...

**Comment by juank-pa** [comment]
Ready

**Comment by subdan** [comment]
Now it works!

I noticed that everyday notifications works but one time notifications doesn't work.

			var date:Date = new Date();
			date.date++; // tomorrow
			date.hours = 9; // at 9:00
			date.minutes = 0;
			date.seconds = 0;
			date.milliseconds = 0;

			var dateString:String = new Date().time.toString();
			var notificationID:String = dateString.substr(0, dateString.length - 3);
			
			var notification:Notification = new Notification();
			notification.title = "title";
			notification.body = "message";
			notification.actionLabel = "label";
			notification.fireDate = date;
			notification.numberAnnotation = 0;
			notification.actionData = {sampleData: "Hello World!"};

			notificationManager.notifyUser(notificationID.toString(), notification);

Could you check it on your device?

**Comment by juank-pa** [comment]
@subdan  iOS or Android?

**Comment by subdan** [comment]
@juank-pa iOS

**Comment by juank-pa** [comment]
@subdan I have tested on dates triggering after seconds, minutes and hours and they all work fine. Haven't tried for day and higher trigger dates. The only thing I can think of is maybe an issue with a timezone mismatch between AIR and the device. Right now I'm using the default timezone which means it uses the timezone set for the application which by default I guess is the same as the system timezone. I'll keep looking at it to see if I find anything but I doubt there will be solutions anytime soon.

**Comment by juank-pa** [comment]
I'm closing this issue because it was already fixed. The other issue with the triggering system requires some research for edge cases and another issue ticket.

**Comment by subdan** [comment]
Ok.

**Comment by subdan** [comment]
I tried to use your sample.as file to check my notifications. It works!

**Comment by juank-pa** [comment]
I recommend trying some things here and there and once you have a better idea on the conditions of the bug please help me opening a new issue so we can talk it further. Thanks in advance.

**Comment by juank-pa** [comment]
@subdan I really recommend you to use version 1.0.6. I found the bug related to notifications not triggering again. It was really sneaky though.

**Comment by subdan** [comment]
@juank-pa Thanks. I will use 1.0.6.

**Comment by juank-pa** [comment]
You are welcome to try version 1.2.0. Is a lot lighter than previous versions and added more features like background button actions and text field actions.

**Comment by subdan** [comment]
Thanks!
