### ISSUE TITLE
The extension context does not have a method with the name ffiInit

### ISSUE THREAD

**Issue by Vadimledyaev** [juank-pa/JKLocalNotifications-ANE#42]
Hi there and thanks for your awesome work!

I've faced a problem running the ANE on Android (v 1.2.0):
**The extension context does not have a method with the name ffiInit**

Does this happen because  support-v4 and compat  were removed?

Best,
V

**Comment by juank-pa** [comment]
Do previous builds work for you?
Are you using other ANEs aside from mine?
It could be related to support-v4 being removed if you were using other ANEs that depended on it and you manually removed or decided not to include support-v4 as a separate library, because it was previously causing collisions.

**Comment by Vadimledyaev** [comment]
No, the app doesn't even start (got popup message saying "Application MYAPPNAME was stopped")

**Comment by juank-pa** [comment]
Please post the following information:
* AIR SDK version used.
* SWF version used.
* Android API SDK target used.
* (If possible) a failing sample with only this ANE included.
* Device model used for the tests.
* Android OS version on device.

**Comment by Vadimledyaev** [comment]
Thanks for the quick answer!
I'm using **Flex 4.6.0, AIR 28.0**
SWF version 37 ( air version 26 <application xmlns="http://ns.adobe.com/air/application/26.0"> )
Android version in application.xml:
```
<uses-sdk android:minSdkVersion="16"/>
   <uses-sdk android:targetSdkVersion="24"/>
```

- I'll build a bare minimum project and would  send it to you if it fails to launch, too

**Comment by Vadimledyaev** [comment]
Android version in application.xml:
```
  <uses-sdk android:minSdkVersion="16"/>
  <uses-sdk android:targetSdkVersion="24"/>
```

**Comment by Sumeet-basak** [comment]
My app used to crash too, but the reason for it to crash was not this plugin. are you using any other SDK/ANE on your project?

**Comment by juank-pa** [comment]
No, this ANE is completely isolated from any other ANE.

**Comment by juank-pa** [comment]
Is there any follow up with this?

**Comment by Sumeet-basak** [comment]
Sorry for the delayed response. i just tested out the build and it works like a charm.

Thank you.

________________________________

**Comment by juank-pa** [comment]
@Vadimledyaev any news with this so I can consider this closed
