### ISSUE TITLE
The notification sounds do not play on Android

### ISSUE THREAD

**Issue by Tpman** [juank-pa/JKLocalNotifications-ANE#52]
Thank you for your great ANE.

I used your sample code below
notification.soundName = "fx05.wav";

Notification on Android is run, but the sounds do not play.
When we comment out code, the device's default sound was played.

"fx05.wav" file is located in the image below.
![image](https://user-images.githubusercontent.com/13846098/54513668-6a148900-499b-11e9-841f-8f0fd656a614.png)

I need to know what's the problem.
Would you mind if you let me know what is the problem? 
Please help me.

AIR SDK version : 31
Android API SDK target used : android:minSdkVersion="16" android:targetSdkVersion="24"
Android OS version on device : 7.0 & 8.0

**Comment by juank-pa** [comment]
Sorry for the very late response. I was focused on other projects lately and that was why I missed the issue. I'll try to take a look at it this next week but after a quick test its working for me on Android. Maybe it could be related to the AIR SDK version. I haven't updated or even had the time to take a look at AIR updates for some time now.

UPDATE: I was compiling the WIP PR and it was working. I noticed a fix made in that PR that I'll migrate into the master branch as well.

**Comment by juank-pa** [comment]
This is being fixed in PR #53

**Comment by juank-pa** [comment]
Solved on release:
https://github.com/juank-pa/JKLocalNotifications-ANE/releases/tag/v1.4.1
