### ISSUE TITLE
Do not work Local Notifications on Android

### ISSUE THREAD

**Issue by Bes79** [juank-pa/JKLocalNotifications-ANE#9]
Hellow! I am build test project “Sample.apk”, and it is open on my device (Xiaomi redmi note 4), but local notifications not work, nofing happanes when i am push on post button, not any error but not working. Please help! (Sorry for my poor english)

**Comment by juank-pa** [comment]
You can check the latest release @Bes79.
https://github.com/juank-pa/JKLocalNotifications-ANE/releases/tag/v1.0.2

**Comment by juank-pa** [comment]
@Bes79 Please give me your feedback to see if I can mark this issue as closed.

**Comment by dr-mms** [comment]
Versions before 1.0.2 don't work on android while v 1.0.2 shows error on packaging

**Comment by juank-pa** [comment]
@Bes79 Happy to announce the new version v1.1.0 came out of alpha and will temporarily hit beta to allow fixing bugs. You are invited to test it out and provide feedback. And don't forget to watch 
![image](https://user-images.githubusercontent.com/5060527/34040097-3d776100-e160-11e7-965f-0f7d36c22402.png) the repo to get information on new versions and features. New features include: support for sounds on Android, custom action buttons in notifications, Android heads up notifications, and more. Thanks in advance.
